### PR TITLE
First step towards visualization destruction with AR models

### LINKED ISSUE #11912: [Model refactor] Delete visualizations with `Carto::Visualizations`
Push towards `::UserTable` removal. ~Best case scenario, complete removal. Write down the final scope of the issue.~

Support for visualization deletion is needed before `::UserTable` removal, so this was chosen as a first step.

### PR DESCRIPTION
**Pull request by juanignaciosl**
This closes #11912.

Notable things:
- We were not correctly destroying related visualization when destroying a dataset (we used a `delete` instead of `destroy`). Took the chance to move this to the `UserTable` models
- We were not deleting layers when destroying a map (with AR models)
- There was an error (probably since the layer refactor) so that named maps were not being regenerated on layer deletion. Fixed that as well. We didn't notice because there are so many operations already invalidating, that other operations were covering this bad behaviour.

**Acceptance**
Remember to check Rollbar for errors/warnings, including debug traces from user table refactor.

- [x] Delete a visualization in multiple ways
  - [x] Dataset
  - [x] Map
  - [x] Dataset with maps depending on it
  - [x] Via ghost tables (delete dataset via SQL API, run ghost tables)
  - [x] Delete a user with visualizations
  - [x] Delete a visualization with widgets, analyses and overlays.
  - [x] Delete a synced dataset
  - [x] Delete a shared (within org) dataset
  - [x] Delete a shared (within org) map

I did not include acceptance checks for deleting all visualization dependencies, since this is better tested with the specs in this PR.

### CODE REVIEW

File: app/controllers/carto/api/visualizations_controller.rb [hunk 1]
```diff
@@ -121,6 +122,35 @@ def static_map
         redirect_to Carto::StaticMapsURLHelper.new.url_for_static_map(request, @visualization, map_width, map_height)
       end
 
+      def destroy
+        current_viewer_id = current_viewer.id
+        properties = { user_id: current_viewer_id, visualization_id: @visualization.id }
+
+        # Tracking. Can this be moved to the model?
+        if @visualization.derived?
```
Comment (javitonino) [inline app/controllers/carto/api/visualizations_controller.rb]: I did it on purpose, because the dependent visualizations thing only really applies to datasets. I'll revert it, we can do a better job if we move this away from the controller anyway.

File: app/controllers/carto/api/visualizations_controller.rb [hunk 2]
```diff
@@ -151,6 +181,10 @@ def load_visualization
         end
       end
 
+      def ensure_visualization_owned
+        raise Carto::LoadError.new('Visualization not editable', 403) unless @visualization.is_owner?(current_user)
```
Comment (javitonino) [inline app/controllers/carto/api/visualizations_controller.rb]: The only difference in `current_user` and `current_viewer` is when you are logged in as user A in the subdomain of user B. In that case, `current_user` returns `nil` and `current_viewer` returns A.

In this case, if you are touching a visualization in another subdomain, you should get an error, so it doesn't matter which of the helpers we user. However, `is_owner?` does not have a guard against `nil` values, so I'll change it to `current_viewer` just in case. It should not matter anyway due to previous authentication hooks, but let's do the change.

**Comment by javitonino** [comment]
Ready for second round.

**Comment by juanignaciosl** [comment]
@javitonino : although you deserve all the credit, GitHub won't allow me to accept it, because I opened the issue :D.

 👍  Moving to acceptance. Please write down any relevant check that you think that should be tested.

**Comment by javitonino** [comment]
It's just one of those PRs where we end up switching roles 😆. Gave you (me?) the thumbs up, and added acceptance checks (basically, everyway way of destroying a visualization I could think of).

**Comment by juanignaciosl** [comment]
Deleting datasets won't work, it triggers two requests, one https that gets cancelled by a http one that fails because of not being https. You need https to reproduce it.

**Comment by javitonino** [comment]
I don't get why two request are launched, but I looked at the code and I think we are missing an `ssl_required` in the new controller (and we can remote it from the old one).

**Comment by juanignaciosl** [comment]
Deleting a synched dataset with a map triggers [mutual locks](https://wiki.postgresql.org/wiki/Lock_Monitoring#.D0.A1ombination_of_blocked_and_blocking_activity):

```
         952 | postgres     |        16511 | postgres      | DELETE FROM "overlays" WHERE "overlays"."id" = 'cb6f669a-4542-4b6d-92e7-e869f670c4a2'             | DELETE FROM "layers_user_tables" WHERE ("user_table_id" = '5ee863c5-a4c6-49aa-8b26-7b12d02f7f68')
       32446 | postgres     |        16511 | postgres      | DELETE FROM "synchronizations" WHERE ("id" = '8765bf12-1eb2-11e7-b24b-040146742701')              | DELETE FROM "layers_user_tables" WHERE ("user_table_id" = '5ee863c5-a4c6-49aa-8b26-7b12d02f7f68')
       16511 | postgres     |        30265 | postgres      | DELETE FROM "layers_user_tables" WHERE ("user_table_id" = '5ee863c5-a4c6-49aa-8b26-7b12d02f7f68') | DELETE FROM "maps" WHERE "maps"."id" = '6325beb6-1762-4833-8bce-97431b21b974'
         952 | postgres     |        30265 | postgres      | DELETE FROM "overlays" WHERE "overlays"."id" = 'cb6f669a-4542-4b6d-92e7-e869f670c4a2'             | DELETE FROM "maps" WHERE "maps"."id" = '6325beb6-1762-4833-8bce-97431b21b974'
       32446 | postgres     |        30265 | postgres      | DELETE FROM "synchronizations" WHERE ("id" = '8765bf12-1eb2-11e7-b24b-040146742701')              | DELETE FROM "maps" WHERE "maps"."id" = '6325beb6-1762-4833-8bce-97431b21b974'
       16511 | postgres     |        32446 | postgres      | DELETE FROM "layers_user_tables" WHERE ("user_table_id" = '5ee863c5-a4c6-49aa-8b26-7b12d02f7f68') | DELETE FROM "synchronizations" WHERE ("id" = '8765bf12-1eb2-11e7-b24b-040146742701')
         952 | postgres     |        32446 | postgres      | DELETE FROM "overlays" WHERE "overlays"."id" = 'cb6f669a-4542-4b6d-92e7-e869f670c4a2'             | DELETE FROM "synchronizations" WHERE ("id" = '8765bf12-1eb2-11e7-b24b-040146742701')
       16511 | postgres     |          952 | postgres      | DELETE FROM "layers_user_tables" WHERE ("user_table_id" = '5ee863c5-a4c6-49aa-8b26-7b12d02f7f68') | DELETE FROM "overlays" WHERE "overlays"."id" = 'cb6f669a-4542-4b6d-92e7-e869f670c4a2'
       32446 | postgres     |          952 | postgres      | DELETE FROM "synchronizations" WHERE ("id" = '8765bf12-1eb2-11e7-b24b-040146742701')              | DELETE FROM "overlays" WHERE "overlays"."id" = 'cb6f669a-4542-4b6d-92e7-e869f670c4a2'
(9 rows)
```

Without a map it also triggers locks:

```
         952 | postgres     |        16511 | postgres      | DELETE FROM "synchronizations" WHERE ("id" = '74efa0ea-0eeb-11e7-b090-040146742701') | DELETE FROM "user_tables" WHERE "user_tables"."id" = '14396695-8b86-4ccc-b681-f6a654343ea5'
```

It ends after some time, probably thanks to timeout. Back to development.

**Comment by juanignaciosl** [comment]
✨  On 🍏 , --> acceptance

**Comment by juanignaciosl** [comment]
There's an issue deleting a dataset. STR:

1. Go to datasets, select two of them and create a map.
2. Delete one of them.

Expected: its layer gets deleted.

Actual: the layer is not deleted.

File: spec/requests/carto/api/visualizations_controller_spec.rb [hunk 3]
```diff
@@ -1559,6 +1565,76 @@ def first_data_layer_from_response(response)
...
+        expect_visualization_to_be_destroyed(visualization) do
+          expect_visualization_to_be_destroyed(table_visualization) do
+            delete_json(destroy_url(@carto_org_user_1, table_visualization.id)) do |response|
+              expect(response.status).to eq 204
+            end
+          end
+        end
+      end
+
+      it 'destroys a visualization and all of its dependencies (partially dependent)' do
```
Comment (juanignaciosl) [inline spec/requests/carto/api/visualizations_controller_spec.rb]: ❤️  (but the name of the test is wrong, it doesn't destroy the visualization but its dependencies. An explicit check of the visualization is still there (currently implicit behind the reload) would be nice.

**Comment by juanignaciosl** [comment]
@javitonino [deployment fails](http://deploy.int.cartodb.net/view/CartoDB/job/Carto%20-%20deploy%20to%20staging%20(carto.com)/1671/console):

`undefined method `require_dependency' for main:Object`

**Comment by javitonino** [comment]
It seems all our recent problems have to do with `require_dependency` 😅 

I reverted the culprit commit (although this breaks hot-reloading when touching the layer model). It should be fine now. Btw, I forgot to mention in a comment (I only edited the initial one):

>There was an error (probably since the layer refactor) so that named maps were not being regenerated on layer deletion. Fixed that as well. We didn't notice because there are so many operations already invalidating, that other operations were covering this bad behaviour.
